server:
  port: 8055

spring:
  application:
    name: Redis Demo Application
  data:
    redis:
      env: DEV
      host: localhost
      port: 6379
      database: 1
      timeout: 2000
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
          time-between-eviction-runs: 10000




